apiVersion: v1
kind: ConfigMap
metadata:
  name: database-config
  namespace: ecommerce
data:
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_NAME: "ecommerce_db"
  DB_USERNAME: "postgres"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: service-urls
  namespace: ecommerce
data:
  PAYMENT_SERVICE_URL: "http://payment-service:8082"
  NOTIFICATION_SERVICE_URL: "http://notification-service:8083"
  LOGIN_SERVICE_URL: "http://login-service:8080"
  CATALOG_SERVICE_URL: "http://catalog-service:8081"
