apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-efs-pvc
  namespace: ecommerce
  labels:
    app: postgres
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: aws-efs
