apiVersion: v1
kind: Secret
metadata:
  name: database-secret
  namespace: ecommerce
type: Opaque
data:
  DB_PASSWORD: cG9zdGdyZXM=  # base64 encoded "postgres"
  POSTGRES_PASSWORD: cG9zdGdyZXM=  # base64 encoded "postgres"
